# Generated by Django 3.2.6 on 2021-08-18 13:22

import datetime

from django.db import migrations


def set_values_for_teacher(apps, schema_editor):
    Teacher = apps.get_model("application", "Teacher")
    data = Teacher(first_name="Daniil", last_name="Shadrin")
    data.save()


def set_values_for_student(apps, schema_editor):
    Student = apps.get_model("application", "Student")
    data = Student(first_name="Roman", last_name="Petrov")
    data.save()


def set_values_for_homework(apps, schema_editor):
    Homework = apps.get_model("application", "Homework")
    data = Homework(
        text="Learn OOP", created=datetime.datetime.now(), deadline=3, teacher_id=1
    )
    data.save()


def set_values_for_homework_result(apps, schema_editor):
    HomeworkResult = apps.get_model("application", "HomeworkResult")
    data = HomeworkResult(
        homework_id=1,
        student_id=1,
        solution="I have done this hw",
        created=datetime.datetime.now(),
        accepted=0,
    )
    data.save()


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_values_for_teacher),
        migrations.RunPython(set_values_for_student),
        migrations.RunPython(set_values_for_homework),
        migrations.RunPython(set_values_for_homework_result),
    ]
